#include "storage.h"

/* FatFs is generated by CubeMX when FATFS is enabled. */
#include "fatfs.h"
#include "ff.h"

#include <stdio.h>

static FATFS filesystem;

bool storage_mount(void) {
    return f_mount(&filesystem, "", 1) == FR_OK;
}

void storage_unmount(void) {
    (void)f_mount(NULL, "", 0);
}

bool storage_append(const SampleRecord *record) {
    FIL file;
    char line[64];
    UINT written = 0;
    int length = snprintf(line, sizeof(line), "%lu,%u,%u,%u\r\n",
                          (unsigned long)record->timestamp_ms, record->raw,
                          record->filtered, record->millivolts);
    if (length <= 0 || (size_t)length >= sizeof(line)) return false;
    if (f_open(&file, "samples.csv", FA_OPEN_APPEND | FA_WRITE) != FR_OK)
        return false;
    FRESULT result = f_write(&file, line, (UINT)length, &written);
    if (result == FR_OK) result = f_sync(&file);
    (void)f_close(&file);
    return result == FR_OK && written == (UINT)length;
}

bool storage_replay(StorageLineSink sink, void *context) {
    FIL file;
    char line[96];
    if (sink == NULL || f_open(&file, "samples.csv", FA_READ) != FR_OK)
        return false;
    while (f_gets(line, sizeof(line), &file) != NULL) {
        if (!sink(line, context)) {
            (void)f_close(&file);
            return false;
        }
    }
    bool ok = f_error(&file) == 0;
    (void)f_close(&file);
    return ok;
}
