#include "board_port.h"

/* These headers and handles are generated by STM32CubeIDE/CubeMX. */
#include "adc.h"
#include "dac.h"
#include "gpio.h"
#include "i2c.h"
#include "iwdg.h"
#include "main.h"
#include "tim.h"
#include "usart.h"

#include <string.h>

#define EEPROM_I2C_ADDRESS (0x50u << 1u)
#define EEPROM_CONFIG_ADDRESS 0x0000u
#define ADC_TIMEOUT_MS 20u

extern void SystemClock_Config(void);

void board_led_set(bool on) {
    /* Change polarity here if the LED on your board is active-low. */
    HAL_GPIO_WritePin(LED_GPIO_Port, LED_Pin, on ? GPIO_PIN_SET : GPIO_PIN_RESET);
}

void board_led_toggle(void) { HAL_GPIO_TogglePin(LED_GPIO_Port, LED_Pin); }

void board_buzzer_beep(uint16_t duration_ms) {
    HAL_GPIO_WritePin(BUZZER_GPIO_Port, BUZZER_Pin, GPIO_PIN_SET);
    HAL_Delay(duration_ms);
    HAL_GPIO_WritePin(BUZZER_GPIO_Port, BUZZER_Pin, GPIO_PIN_RESET);
}

bool board_key_pressed(void) {
    /* Reference circuit assumes active-low key. */
    return HAL_GPIO_ReadPin(KEY_GPIO_Port, KEY_Pin) == GPIO_PIN_RESET;
}

uint32_t board_millis(void) { return HAL_GetTick(); }
void board_delay_ms(uint32_t duration_ms) { HAL_Delay(duration_ms); }

void board_log(const char *text) {
    (void)board_uart_send((const uint8_t *)text, strlen(text));
}

bool board_uart_send(const uint8_t *data, size_t length) {
    return data != NULL && length <= UINT16_MAX &&
           HAL_UART_Transmit(&huart1, data, (uint16_t)length, 100) == HAL_OK;
}

bool board_adc_read(uint16_t *raw) {
    if (raw == NULL || HAL_ADC_Start(&hadc1) != HAL_OK) return false;
    if (HAL_ADC_PollForConversion(&hadc1, ADC_TIMEOUT_MS) != HAL_OK) {
        (void)HAL_ADC_Stop(&hadc1);
        return false;
    }
    *raw = (uint16_t)HAL_ADC_GetValue(&hadc1);
    return HAL_ADC_Stop(&hadc1) == HAL_OK;
}

bool board_config_load(StoredConfig *config) {
    return config != NULL &&
           HAL_I2C_Mem_Read(&hi2c1, EEPROM_I2C_ADDRESS, EEPROM_CONFIG_ADDRESS,
                            I2C_MEMADD_SIZE_16BIT, (uint8_t *)config,
                            sizeof(*config), 100) == HAL_OK;
}

bool board_config_save(const StoredConfig *config) {
    if (config == NULL) return false;
    if (HAL_I2C_Mem_Write(&hi2c1, EEPROM_I2C_ADDRESS, EEPROM_CONFIG_ADDRESS,
                          I2C_MEMADD_SIZE_16BIT, (uint8_t *)config,
                          sizeof(*config), 100) != HAL_OK) return false;
    HAL_Delay(10); /* AT24Cxx internal write cycle. */
    StoredConfig verify;
    return board_config_load(&verify) &&
           memcmp(&verify, config, sizeof(verify)) == 0;
}

void board_sample_timer_start(uint32_t rate_hz) {
    if (rate_hz == 0) return;
    uint32_t timer_clock_hz = HAL_RCC_GetPCLK1Freq() * 2u;
    uint32_t timer_tick_hz = 10000u;
    __HAL_TIM_SET_PRESCALER(&htim2, (timer_clock_hz / timer_tick_hz) - 1u);
    __HAL_TIM_SET_AUTORELOAD(&htim2, (timer_tick_hz / rate_hz) - 1u);
    __HAL_TIM_SET_COUNTER(&htim2, 0u);
    (void)HAL_TIM_Base_Start_IT(&htim2);
}

void board_sample_timer_stop(void) { (void)HAL_TIM_Base_Stop_IT(&htim2); }
void board_watchdog_refresh(void) { (void)HAL_IWDG_Refresh(&hiwdg); }

void board_enter_stop_mode(void) {
    HAL_SuspendTick();
    HAL_PWR_EnterSTOPMode(PWR_LOWPOWERREGULATOR_ON, PWR_STOPENTRY_WFI);
    /* After wakeup, restore SystemClock_Config generated in main.c. */
    SystemClock_Config();
    HAL_ResumeTick();
}

bool board_dac_dma_start(const uint16_t *samples, size_t count) {
    if (samples == NULL || count == 0 || count > UINT16_MAX) return false;
    return HAL_DAC_Start_DMA(&hdac, DAC_CHANNEL_1, (uint32_t *)samples,
                             (uint32_t)count, DAC_ALIGN_12B_R) == HAL_OK;
}
